// Centralized assets mapping for SYM Egypt Scooters application
export const ASSETS = {
  brand: {
    logoRed: '/assets/brand/sym-logo-red.png',
    logoBadge: '/assets/brand/SYM Logo.png',
    iconSearchWhite: '/assets/brand/icon-search-white.svg',
  },
  hero: {
    hero1: '/assets/hero/husky adv.png',
    hero2: '/assets/hero/cruisym 400.png',
    hero3: '/assets/hero/joymax z300.png',
    huskyAdv: '/assets/hero/husky adv.png',
    cruisym400: '/assets/hero/cruisym 400.png',
    joymaxZ300: '/assets/hero/joymax z300.png',
  },
  categories: {
    maxiScooter: '/assets/categories/maxiscooter 1.png',
    urbanDaily: '/assets/categories/urban daily.png',
    powerSport: '/assets/categories/power sport.png',
    classicScooter: '/assets/categories/classic scooter.png',
    allRoad: '/assets/categories/all-road.png',
    casual: '/assets/categories/Casual.png',
    service: '/assets/categories/service.webp',
    whereToBuy: '/assets/categories/where.webp',
  },
  banners: {
    topBanner: '/assets/banners/top-banner.jpg',
    subbannerNinebot: '/assets/banners/subbanner-ninebot.svg',
    subbannerSegway: '/assets/banners/subbanner-segway.svg',
    subbannerZt3pro: '/assets/banners/subbanner-zt3pro.svg',
    no1Cards430: '/assets/banners/no1-cards-430.png',
    no1Cards768: '/assets/banners/no1-cards-768.png',
    no1Cards960: '/assets/banners/no1-cards-960.png',
    no1Cards1200: '/assets/banners/no1-cards-1200.png',
    no1Cards1440: '/assets/banners/no1-cards-1440.png',
    no1Cards1920: '/assets/banners/no1-cards-1920.png',
  },
  products: {
    bup275u: '/assets/products/bup-275u.png',
    cruisym400: '/assets/products/cruisym-400.png',
    fiddle2: '/assets/products/fiddle-2.png',
    huskyAdv: '/assets/products/husky-adv.png',
    husky: '/assets/products/husky.png',
    jet14Add: '/assets/products/jet14-add.png',
    jet14Evo: '/assets/products/jet14-evo.png',
    nhx200: '/assets/products/nhx-200.png',
    nht200: '/assets/products/nht-200.png',
    oldSt: '/assets/products/old-st.png',
    newSt: '/assets/products/new-st.png',
    newStNobg: '/assets/products/new-st-nobg.png',
    jetX: '/assets/products/jet-x.jpg',
    jetXNobg: '/assets/products/jet-x-nobg.png',
    jetXNobgAlt: '/assets/products/jet-x-nobg-alt.png',
    ekickscooterGt3pro: '/assets/products/ekickscooter-gt3pro.png',
  },
} as const;
